### ISSUE TITLE
Can not REMOVE Hail as Device Owner

### ISSUE THREAD

**Issue by rahaaatul** [aistra0528/Hail#105]
Using this command give me this error:

> dpm remove-active-admin com.aistra.hail/com.aistra.hail.receiver.DeviceAdminReceiver

```
java.lang.SecurityException: Attempt to remove non-test admin ComponentInfo{com.aistra.hail/com.aistra.hail.receiver.DeviceAdminReceiver} 0
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2388)
        at android.os.Parcel.createException(Parcel.java:2372)
        at android.os.Parcel.readException(Parcel.java:2355)
        at android.os.Parcel.readException(Parcel.java:2297)
        at android.app.admin.IDevicePolicyManager$Stub$Proxy.forceRemoveActiveAdmin(IDevicePolicyManager.java:8695)
        at com.android.commands.dpm.Dpm.runRemoveActiveAdmin(Dpm.java:222)
        at com.android.commands.dpm.Dpm.onRun(Dpm.java:121)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:60)
        at com.android.commands.dpm.Dpm.main(Dpm.java:41)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:433)
Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.devicepolicy.DevicePolicyManagerService.lambda$forceRemoveActiveAdmin$6$DevicePolicyManagerService(DevicePolicyManagerService.java:4689)
        at com.android.server.devicepolicy.-$$Lambda$DevicePolicyManagerService$kMbNyFCPm-YTFbzEmBLvLJbyLPM.runOrThrow(Unknown Source:6)
        at android.os.Binder.withCleanCallingIdentity(Binder.java:381)
        at com.android.server.devicepolicy.DevicePolicyManagerService$Injector.binderWithCleanCallingIdentity(DevicePolicyManagerService.java:2398)
        at com.android.server.devicepolicy.DevicePolicyManagerService.forceRemoveActiveAdmin(DevicePolicyManagerService.java:4686)
```
- Tried to deactivate device admin via Settings > Device Admin but the option to deactivate is greyed out.
- I tried to uninstall from app drawer, but it does not get uninstalled. 
- Tried to do it from the settings but the option is greyed out.
- Also tried to do it with adb command:

> pm uninstall com.aistra.hail

`Failure [DELETE_FAILED_INTERNAL_ERROR]`

How can I remove the device admin? would you be kind enough to look into this [article](https://itecnote.com/tecnote/android-how-to-remove-set-device-owner-in-android-dpm/)? It says:
> By specifying the android:testOnly="true" attribute in the AndroidManifest.xml it will be possible to uninstall the app or remove admin with `adb shell dpm remove-active-admin package.name/MyDeviceAdminReceiver`

**Comment by rahaaatul** [comment]
Actually, figured it out. I had to **uninstall it from inside the Hail app**. My bad.
