### ISSUE TITLE
无法启用设备所有者模式的解决办法

### ISSUE THREAD

**Issue by hydroakri** [aistra0528/Hail#24]
使用adb激活设备所有者模式时提示设备已有存在的用户
````
adb server is out of date. killing... * daemon started successfully * java.lang.IllegalStateException: Not allowed to set the device owner because there are already several users on the device at android.os.Parcel.readException(Parcel.java:1629) at android.os.Parcel.readException(Parcel.java:1574) at android.app.admin.IDevicePolicyManager$Stub$Proxy.setDeviceOwner(IDevicePolicyManager.java:5146) at com.android.commands.dpm.Dpm.runSetDeviceOwner(Dpm.java:114) at com.android.commands.dpm.Dpm.onRun(Dpm.java:82) at com.android.internal.os.BaseCommand.run(BaseCommand.java:47) at com.android.commands.dpm.Dpm.main(Dpm.java:38) at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method) at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:257) 
````
复现：当设备存在支付宝抖音等软件时无法激活，且查看`adb shell pm list users`时无其他用户

解决方法：卸载支付宝等，并删除设备上其他账号后激活设备所有者，再重新安装支付宝即可

**Comment by chengnan049** [comment]
同时也给大家提供一个思路，使用 小黑屋 作者开发的 黑色小屋 （现已下架，某下载站可找到资源，支持 冰箱 小黑屋 激活），先使用 `adb tpcip 5555` 进行网络 adb ，随后使用 黑色小屋 激活 冰箱 或 小黑屋，最后在软件内撤销掉权限及时使用命令激活即可

PS：此方法可清除 vivo 设备账户，但不要用作歪门邪道
