### ISSUE TITLE
Device Owner not working as expected

### ISSUE THREAD

**Issue by bonswouar** [aistra0528/Hail#282]
Maybe I misunderstand Android settings, but when I go to `Settings > Security & privacy > More security & privacy > Device admin apps`, I can see that `Hail` is `enabled`.
Isn't it the same thing as "Device owner"?

If I run `adb shell dpm set-device-owner com.aistral.hail/.receiver.DeviceAdminReceiver` I get:
```
com.aistral.hail/.receiver.DeviceAdminReceiver was already an admin for user 0. No need to set it again

Exception occurred while executing 'set-device-owner':
java.lang.IllegalStateException: Not allowed to set the device owner because there are already some accounts on the device.
[...]
```
So it looks like it's already set, although those 2 error messages seem to contradict themselves..

I saw I might be able to reset the device owner with a factory reset, but not sure it will work, and I don't really want to factory reset my phone.
I'd like to avoid rooting the device just for this app if possible?
Thanks!

- OnePlus 5
- LineageOS 21 / Android 14

**Comment by candroid-man** [comment]
I am also experiencing this issue on a non-rooted Pixel 8 with GrapheneOS. Here is my full terminal output:
```
candroid_man@fedora~$ adb shell dpm set-device-owner com.aistra.hail/.receiver.DeviceAdminReceiver

Exception occurred while executing 'set-device-owner':
java.lang.IllegalStateException: Not allowed to set the device owner because there are already some accounts on the device.
	at com.android.server.devicepolicy.DevicePolicyManagerService.enforceCanSetDeviceOwnerLocked(DevicePolicyManagerService.java:11171)
	at com.android.server.devicepolicy.DevicePolicyManagerService.setDeviceOwner(DevicePolicyManagerService.java:9807)
	at com.android.server.devicepolicy.DevicePolicyManagerServiceShellCommand.runSetDeviceOwner(DevicePolicyManagerServiceShellCommand.java:285)
	at com.android.server.devicepolicy.DevicePolicyManagerServiceShellCommand.onCommand(DevicePolicyManagerServiceShellCommand.java:90)
	at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
	at android.os.ShellCommand.exec(ShellCommand.java:38)
	at com.android.server.devicepolicy.DevicePolicyManagerService.onShellCommand(DevicePolicyManagerService.java:11592)
	at android.os.Binder.shellCommand(Binder.java:1140)
	at android.os.Binder.onTransact(Binder.java:957)
	at android.app.admin.IDevicePolicyManager$Stub.onTransact(IDevicePolicyManager.java:6457)
	at android.os.Binder.execTransactInternal(Binder.java:1425)
	at android.os.Binder.execTransact(Binder.java:1359)

```

**Comment by bonswouar** [comment]
FYI I found out that Hail instructions are a bit misleading:
Apparently `dpm set-device-owner` won't work on many _(most?)_ phones, as lots of apps are registered as Accounts _(even if they don't appear in Android Accounts settings)_, preventing changing the device owner for some reason.

---

Basically the cleaner solution I found _(inspired by [this discussion](https://github.com/iamr0s/Dhizuku/discussions/19#discussioncomment-9688625))_ was:

1. Install [Shizuku](https://shizuku.rikka.app)
2. `adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh` to run Shizuku service
3.  Use Hail with Shizuku

> The main issue if stopping at this step, is that **Shizuku will be disabled at each reboot** (and Hail permissions). So frozen apps can't be unfrozen easily (not without `adb`) and vice versa, which isn't ideal imo.

So what I ended up doing after was:

4. Use [aShell](https://gitlab.com/sunilpaulmathew/ashell) or some similar app that can list Accounts (command `dumpsys account`) using Shizuku api
5. (Temporary) freeze all those apps in Hail using "Shizuku - Disable" mode
6. Reboot (really needed in my case!)
7. Then two possible solutions:
    - **A.** Set the device owner to Hail if you only care about this app
      - `adb shell dpm set-device-owner com.aistral.hail/.receiver.DeviceAdminReceiver` should work now 
    - **B.** Or use Dhizuku to have permanent root-like permissions - for some potential other apps in the future - without the need of `adb`
      - Install [Dhizuku](https://github.com/iamr0s/Dhizuku)
      - `adb shell dpm set-device-owner com.rosan.dhizuku/.server.DhizukuDAReceiver`
8. Still using "Shizuku - Disable" mode in Hail, un-freeze the apps from step 5.
9. Switch to the appropriate mode in Hail (Owner for **A.** or Dhizuku for **B.**)
